#ifndef DUCKSPT_appvar_include_file
#define DUCKSPT_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define sizeof_palette 60
#define palette (DUCKSPT_appvar[0])
#define dog_palette_offset 0
#define dog_bird_1_width 43
#define dog_bird_1_height 40
#define DUCKSPT_dog_dog_bird_1_index 1
#define dog_bird_1 ((gfx_sprite_t*)DUCKSPT_appvar[1])
#define dog_bird_2_width 56
#define dog_bird_2_height 40
#define DUCKSPT_dog_dog_bird_2_index 2
#define dog_bird_2 ((gfx_sprite_t*)DUCKSPT_appvar[2])
#define dog_jump_1_width 35
#define dog_jump_1_height 48
#define DUCKSPT_dog_dog_jump_1_index 3
#define dog_jump_1 ((gfx_sprite_t*)DUCKSPT_appvar[3])
#define dog_jump_2_width 33
#define dog_jump_2_height 32
#define DUCKSPT_dog_dog_jump_2_index 4
#define dog_jump_2 ((gfx_sprite_t*)DUCKSPT_appvar[4])
#define dog_laugh_1_width 29
#define dog_laugh_1_height 40
#define DUCKSPT_dog_dog_laugh_1_index 5
#define dog_laugh_1 ((gfx_sprite_t*)DUCKSPT_appvar[5])
#define dog_laugh_2_width 29
#define dog_laugh_2_height 40
#define DUCKSPT_dog_dog_laugh_2_index 6
#define dog_laugh_2 ((gfx_sprite_t*)DUCKSPT_appvar[6])
#define dog_walk_0_width 55
#define dog_walk_0_height 40
#define DUCKSPT_dog_dog_walk_0_index 7
#define dog_walk_0 ((gfx_sprite_t*)DUCKSPT_appvar[7])
#define dog_walk_1_width 51
#define dog_walk_1_height 43
#define DUCKSPT_dog_dog_walk_1_index 8
#define dog_walk_1 ((gfx_sprite_t*)DUCKSPT_appvar[8])
#define dog_walk_2_width 53
#define dog_walk_2_height 40
#define DUCKSPT_dog_dog_walk_2_index 9
#define dog_walk_2 ((gfx_sprite_t*)DUCKSPT_appvar[9])
#define dog_walk_3_width 51
#define dog_walk_3_height 43
#define DUCKSPT_dog_dog_walk_3_index 10
#define dog_walk_3 ((gfx_sprite_t*)DUCKSPT_appvar[10])
#define dog_walk_4_width 55
#define dog_walk_4_height 40
#define DUCKSPT_dog_dog_walk_4_index 11
#define dog_walk_4 ((gfx_sprite_t*)DUCKSPT_appvar[11])
#define dog_walk_5_width 53
#define dog_walk_5_height 40
#define DUCKSPT_dog_dog_walk_5_index 12
#define dog_walk_5 ((gfx_sprite_t*)DUCKSPT_appvar[12])
#define dog_walk_6_width 53
#define dog_walk_6_height 48
#define DUCKSPT_dog_dog_walk_6_index 13
#define dog_walk_6 ((gfx_sprite_t*)DUCKSPT_appvar[13])
#define ducks_palette_offset 0
#define Duck_A_1_width 34
#define Duck_A_1_height 29
#define DUCKSPT_ducks_Duck_A_1_index 14
#define Duck_A_1 ((gfx_sprite_t*)DUCKSPT_appvar[14])
#define Duck_A_2_width 34
#define Duck_A_2_height 29
#define DUCKSPT_ducks_Duck_A_2_index 15
#define Duck_A_2 ((gfx_sprite_t*)DUCKSPT_appvar[15])
#define Duck_A_3_width 34
#define Duck_A_3_height 29
#define DUCKSPT_ducks_Duck_A_3_index 16
#define Duck_A_3 ((gfx_sprite_t*)DUCKSPT_appvar[16])
#define Duck_B_1_width 32
#define Duck_B_1_height 31
#define DUCKSPT_ducks_Duck_B_1_index 17
#define Duck_B_1 ((gfx_sprite_t*)DUCKSPT_appvar[17])
#define Duck_B_2_width 32
#define Duck_B_2_height 31
#define DUCKSPT_ducks_Duck_B_2_index 18
#define Duck_B_2 ((gfx_sprite_t*)DUCKSPT_appvar[18])
#define Duck_B_3_width 32
#define Duck_B_3_height 31
#define DUCKSPT_ducks_Duck_B_3_index 19
#define Duck_B_3 ((gfx_sprite_t*)DUCKSPT_appvar[19])
#define Duck_Fall_1_width 18
#define Duck_Fall_1_height 31
#define DUCKSPT_ducks_Duck_Fall_1_index 20
#define Duck_Fall_1 ((gfx_sprite_t*)DUCKSPT_appvar[20])
#define Duck_Fall_2_width 18
#define Duck_Fall_2_height 31
#define DUCKSPT_ducks_Duck_Fall_2_index 21
#define Duck_Fall_2 ((gfx_sprite_t*)DUCKSPT_appvar[21])
#define Duck_Flyaway_1_width 32
#define Duck_Flyaway_1_height 35
#define DUCKSPT_ducks_Duck_Flyaway_1_index 22
#define Duck_Flyaway_1 ((gfx_sprite_t*)DUCKSPT_appvar[22])
#define Duck_Flyaway_2_width 32
#define Duck_Flyaway_2_height 35
#define DUCKSPT_ducks_Duck_Flyaway_2_index 23
#define Duck_Flyaway_2 ((gfx_sprite_t*)DUCKSPT_appvar[23])
#define Duck_Flyaway_3_width 32
#define Duck_Flyaway_3_height 35
#define DUCKSPT_ducks_Duck_Flyaway_3_index 24
#define Duck_Flyaway_3 ((gfx_sprite_t*)DUCKSPT_appvar[24])
#define Duck_Shot_width 31
#define Duck_Shot_height 29
#define DUCKSPT_ducks_Duck_Shot_index 25
#define Duck_Shot ((gfx_sprite_t*)DUCKSPT_appvar[25])
#define Duckb_A_1_width 34
#define Duckb_A_1_height 29
#define DUCKSPT_ducks_Duckb_A_1_index 26
#define Duckb_A_1 ((gfx_sprite_t*)DUCKSPT_appvar[26])
#define Duckb_A_2_width 34
#define Duckb_A_2_height 29
#define DUCKSPT_ducks_Duckb_A_2_index 27
#define Duckb_A_2 ((gfx_sprite_t*)DUCKSPT_appvar[27])
#define Duckb_A_3_width 34
#define Duckb_A_3_height 29
#define DUCKSPT_ducks_Duckb_A_3_index 28
#define Duckb_A_3 ((gfx_sprite_t*)DUCKSPT_appvar[28])
#define Duckb_B_1_width 32
#define Duckb_B_1_height 31
#define DUCKSPT_ducks_Duckb_B_1_index 29
#define Duckb_B_1 ((gfx_sprite_t*)DUCKSPT_appvar[29])
#define Duckb_B_2_width 32
#define Duckb_B_2_height 31
#define DUCKSPT_ducks_Duckb_B_2_index 30
#define Duckb_B_2 ((gfx_sprite_t*)DUCKSPT_appvar[30])
#define Duckb_B_3_width 32
#define Duckb_B_3_height 31
#define DUCKSPT_ducks_Duckb_B_3_index 31
#define Duckb_B_3 ((gfx_sprite_t*)DUCKSPT_appvar[31])
#define Duckb_Fall_1_width 18
#define Duckb_Fall_1_height 31
#define DUCKSPT_ducks_Duckb_Fall_1_index 32
#define Duckb_Fall_1 ((gfx_sprite_t*)DUCKSPT_appvar[32])
#define Duckb_Fall_2_width 18
#define Duckb_Fall_2_height 31
#define DUCKSPT_ducks_Duckb_Fall_2_index 33
#define Duckb_Fall_2 ((gfx_sprite_t*)DUCKSPT_appvar[33])
#define Duckb_Flyaway_1_width 32
#define Duckb_Flyaway_1_height 35
#define DUCKSPT_ducks_Duckb_Flyaway_1_index 34
#define Duckb_Flyaway_1 ((gfx_sprite_t*)DUCKSPT_appvar[34])
#define Duckb_Flyaway_2_width 32
#define Duckb_Flyaway_2_height 35
#define DUCKSPT_ducks_Duckb_Flyaway_2_index 35
#define Duckb_Flyaway_2 ((gfx_sprite_t*)DUCKSPT_appvar[35])
#define Duckb_Flyaway_3_width 32
#define Duckb_Flyaway_3_height 35
#define DUCKSPT_ducks_Duckb_Flyaway_3_index 36
#define Duckb_Flyaway_3 ((gfx_sprite_t*)DUCKSPT_appvar[36])
#define Duckb_Shot_width 31
#define Duckb_Shot_height 29
#define DUCKSPT_ducks_Duckb_Shot_index 37
#define Duckb_Shot ((gfx_sprite_t*)DUCKSPT_appvar[37])
#define Duckc_A_1_width 34
#define Duckc_A_1_height 29
#define DUCKSPT_ducks_Duckc_A_1_index 38
#define Duckc_A_1 ((gfx_sprite_t*)DUCKSPT_appvar[38])
#define Duckc_A_2_width 34
#define Duckc_A_2_height 29
#define DUCKSPT_ducks_Duckc_A_2_index 39
#define Duckc_A_2 ((gfx_sprite_t*)DUCKSPT_appvar[39])
#define Duckc_A_3_width 34
#define Duckc_A_3_height 29
#define DUCKSPT_ducks_Duckc_A_3_index 40
#define Duckc_A_3 ((gfx_sprite_t*)DUCKSPT_appvar[40])
#define Duckc_B_1_width 32
#define Duckc_B_1_height 31
#define DUCKSPT_ducks_Duckc_B_1_index 41
#define Duckc_B_1 ((gfx_sprite_t*)DUCKSPT_appvar[41])
#define Duckc_B_2_width 32
#define Duckc_B_2_height 31
#define DUCKSPT_ducks_Duckc_B_2_index 42
#define Duckc_B_2 ((gfx_sprite_t*)DUCKSPT_appvar[42])
#define Duckc_B_3_width 32
#define Duckc_B_3_height 31
#define DUCKSPT_ducks_Duckc_B_3_index 43
#define Duckc_B_3 ((gfx_sprite_t*)DUCKSPT_appvar[43])
#define Duckc_Fall_1_width 18
#define Duckc_Fall_1_height 31
#define DUCKSPT_ducks_Duckc_Fall_1_index 44
#define Duckc_Fall_1 ((gfx_sprite_t*)DUCKSPT_appvar[44])
#define Duckc_Fall_2_width 18
#define Duckc_Fall_2_height 31
#define DUCKSPT_ducks_Duckc_Fall_2_index 45
#define Duckc_Fall_2 ((gfx_sprite_t*)DUCKSPT_appvar[45])
#define Duckc_Flyaway_1_width 32
#define Duckc_Flyaway_1_height 35
#define DUCKSPT_ducks_Duckc_Flyaway_1_index 46
#define Duckc_Flyaway_1 ((gfx_sprite_t*)DUCKSPT_appvar[46])
#define Duckc_Flyaway_2_width 32
#define Duckc_Flyaway_2_height 35
#define DUCKSPT_ducks_Duckc_Flyaway_2_index 47
#define Duckc_Flyaway_2 ((gfx_sprite_t*)DUCKSPT_appvar[47])
#define Duckc_Flyaway_3_width 32
#define Duckc_Flyaway_3_height 35
#define DUCKSPT_ducks_Duckc_Flyaway_3_index 48
#define Duckc_Flyaway_3 ((gfx_sprite_t*)DUCKSPT_appvar[48])
#define Duckc_Shot_width 31
#define Duckc_Shot_height 29
#define DUCKSPT_ducks_Duckc_Shot_index 49
#define Duckc_Shot ((gfx_sprite_t*)DUCKSPT_appvar[49])
#define game_palette_offset 0
#define bg_bush_width 32
#define bg_bush_height 40
#define DUCKSPT_game_bg_bush_compressed_index 50
#define bg_bush_compressed DUCKSPT_appvar[50]
#define bg_ground_width 255
#define bg_ground_height 56
#define DUCKSPT_game_bg_ground_compressed_index 51
#define bg_ground_compressed DUCKSPT_appvar[51]
#define bg_tree_width 69
#define bg_tree_height 140
#define DUCKSPT_game_bg_tree_compressed_index 52
#define bg_tree_compressed DUCKSPT_appvar[52]
#define panel_icon_1_width 7
#define panel_icon_1_height 7
#define DUCKSPT_game_panel_icon_1_compressed_index 53
#define panel_icon_1_compressed DUCKSPT_appvar[53]
#define panel_icon_2_width 7
#define panel_icon_2_height 7
#define DUCKSPT_game_panel_icon_2_compressed_index 54
#define panel_icon_2_compressed DUCKSPT_appvar[54]
#define panel_icon_3_width 7
#define panel_icon_3_height 7
#define DUCKSPT_game_panel_icon_3_compressed_index 55
#define panel_icon_3_compressed DUCKSPT_appvar[55]
#define bullet_width 4
#define bullet_height 7
#define DUCKSPT_game_bullet_compressed_index 56
#define bullet_compressed DUCKSPT_appvar[56]
#define bullet_board_width 29
#define bullet_board_height 21
#define DUCKSPT_game_bullet_board_compressed_index 57
#define bullet_board_compressed DUCKSPT_appvar[57]
#define c_ground_width 255
#define c_ground_height 43
#define DUCKSPT_game_c_ground_compressed_index 58
#define c_ground_compressed DUCKSPT_appvar[58]
#define c_mountain_width 255
#define c_mountain_height 45
#define DUCKSPT_game_c_mountain_compressed_index 59
#define c_mountain_compressed DUCKSPT_appvar[59]
#define c_panel_width 255
#define c_panel_height 8
#define DUCKSPT_game_c_panel_compressed_index 60
#define c_panel_compressed DUCKSPT_appvar[60]
#define crosshair_width 25
#define crosshair_height 25
#define DUCKSPT_game_crosshair_compressed_index 61
#define crosshair_compressed DUCKSPT_appvar[61]
#define fly_away_width 73
#define fly_away_height 17
#define DUCKSPT_game_fly_away_compressed_index 62
#define fly_away_compressed DUCKSPT_appvar[62]
#define kill_board_width 117
#define kill_board_height 21
#define DUCKSPT_game_kill_board_compressed_index 63
#define kill_board_compressed DUCKSPT_appvar[63]
#define pause_width 49
#define pause_height 33
#define DUCKSPT_game_pause_compressed_index 64
#define pause_compressed DUCKSPT_appvar[64]
#define score_board_width 53
#define score_board_height 21
#define DUCKSPT_game_score_board_compressed_index 65
#define score_board_compressed DUCKSPT_appvar[65]
#define menu_palette_offset 0
#define cr_text_width 200
#define cr_text_height 10
#define DUCKSPT_menu_cr_text_compressed_index 66
#define cr_text_compressed DUCKSPT_appvar[66]
#define game_type_text_width 115
#define game_type_text_height 39
#define DUCKSPT_menu_game_type_text_compressed_index 67
#define game_type_text_compressed DUCKSPT_appvar[67]
#define game_types_width 52
#define game_types_height 39
#define DUCKSPT_menu_game_types_compressed_index 68
#define game_types_compressed DUCKSPT_appvar[68]
#define menu_arrow_width 12
#define menu_arrow_height 10
#define DUCKSPT_menu_menu_arrow_compressed_index 69
#define menu_arrow_compressed DUCKSPT_appvar[69]
#define Title_Menu_width 143
#define Title_Menu_height 65
#define DUCKSPT_menu_Title_Menu_compressed_index 70
#define Title_Menu_compressed DUCKSPT_appvar[70]
#define DUCKSPT_entries_num 71
extern unsigned char *DUCKSPT_appvar[71];
unsigned char DUCKSPT_init(void);

#ifdef __cplusplus
}
#endif

#endif
